# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'point_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.setIndexBox = QtWidgets.QSpinBox(self.centralwidget)
        self.setIndexBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setIndexBox.setObjectName("setIndexBox")
        self.horizontalLayout_6.addWidget(self.setIndexBox)
        self.autoFeed = QtWidgets.QCheckBox(self.centralwidget)
        self.autoFeed.setObjectName("autoFeed")
        self.horizontalLayout_6.addWidget(self.autoFeed)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.im1 = MplWidget(self.centralwidget)
        self.im1.setObjectName("im1")
        self.horizontalLayout.addWidget(self.im1)
        self.im2 = MplWidget(self.centralwidget)
        self.im2.setObjectName("im2")
        self.horizontalLayout.addWidget(self.im2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.img1IndexBox = QtWidgets.QSpinBox(self.centralwidget)
        self.img1IndexBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.img1IndexBox.setObjectName("img1IndexBox")
        self.horizontalLayout_4.addWidget(self.img1IndexBox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.img2IndexBox = QtWidgets.QSpinBox(self.centralwidget)
        self.img2IndexBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.img2IndexBox.setObjectName("img2IndexBox")
        self.horizontalLayout_5.addWidget(self.img2IndexBox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 22))
        self.menubar.setObjectName("menubar")
        self.menuSAFL_Point = QtWidgets.QMenu(self.menubar)
        self.menuSAFL_Point.setObjectName("menuSAFL_Point")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClear_matches = QtWidgets.QAction(MainWindow)
        self.actionClear_matches.setObjectName("actionClear_matches")
        self.menuSAFL_Point.addAction(self.actionOpen)
        self.menuSAFL_Point.addAction(self.actionSave)
        self.menuSAFL_Point.addAction(self.actionQuit)
        self.menuSAFL_Point.addSeparator()
        self.menuSAFL_Point.addAction(self.actionClear_matches)
        self.menubar.addAction(self.menuSAFL_Point.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SAFL Point"))
        self.label_3.setText(_translate("MainWindow", "Point:"))
        self.autoFeed.setText(_translate("MainWindow", "Auto feed"))
        self.label.setText(_translate("MainWindow", "Image:"))
        self.label_2.setText(_translate("MainWindow", "Image:"))
        self.menuSAFL_Point.setTitle(_translate("MainWindow", "&SAFL Point"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionClear_matches.setText(_translate("MainWindow", "Clear matches"))

from mplwidget import MplWidget
